version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b 0.0.0.0"

    #use networks in order to make containers communicate
    networks:
      - voxgroup_application-network

    depends_on:
      - api


networks:
  voxgroup_application-network:
    name: voxgroup_application-network
    external: true